theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs

# Site settings
title: Isochrones

# Aux links for the upper right navigation
aux_links:
  "View source on GitHub":
    - "//github.com/scc-pi/isochrones"